schema_version = "1.0.0"

id = "texel_density_checker"
version = "2023.2.2"
name = "Texel Density Checker"
tagline = "Toolset for working with Texel Density"
maintainer = "Ivan Vostrikov <mrven1989@gmail.com>"
type = "add-on"

website = "https://github.com/mrven/Blender-Texel-Density-Checker"

tags = ["3D View", "Object", "UV"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]